export const districtOptions = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Colombo',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matara',
  'Matale',
  'Monaragala',
  'Nuwara Eliya',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Trincomalee',
  'Vavuniya',
];

export const listingTypeOptions = [
  'Attraction',
  'Beach',
  'Mountain',
  'Forest',
  'City',
  'Village',
  'Historical Site',
];

export const attractionTypeOptions = [
  'Attraction',
  'Animals',
  'Archaeolgy',
  'Art',
  'Botanical Gardens',
  'Down South Beach',
  'East-Beach',
  'Entertainment',
  'Hiking',
  'History & Culture',
  'Lake',
  'Rivers',
  'Museum',
  'Nature',
  'North-Beach',
  'Religious Place',
  'Snorkelling & Diving',
  'Surf',
  'Water Falls',
  'Western-Beach',
  'Beach',
  'Mountain',
  'Forest',
  'City',
  'Village',
  'Historical Site',
];
